deployment:
  tasks:
    - export SRC="$DEPLOYMENT_SOURCE"
    - export DEST="$HOME/public_html/snco"
    - '[ -d "$DEST" ] || mkdir -p "$DEST"'
    - rsync -a --delete --exclude=".git" "$SRC"/ "$DEST"/
    - find "$DEST" -type d -exec chmod 755 {} \;
    - find "$DEST" -type f -exec chmod 644 {} \;
