name: Deploy via FTPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Upload to cPanel via FTPS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_TARGET }}/
          log-level: standard
          timeout: 60000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.zip
            **/*.tar
            **/*.tar.gz
            **/*.tgz
            **/*.md
            **/README*
